version: '3.4'

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/sites/:/etc/nginx/sites-available
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bepositive.rule=Host(`bepositive.local`)"
        - "traefik.docker.network=traefik_proxy"
    networks:
        - traefik_proxy
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./:/var/www/html:cached
    depends_on:
      - postgres
    links:
        - postgres
    environment:
      NETTE_DEBUG: 1
      PHP_EXTENSION_XDEBUG: 1
      PHP_EXTENSION_PGSQL: 1
      PHP_EXTENSION_PDO_PGSQL: 1
      PHP_EXTENSION_MYSQLI: 1
      STARTUP_COMMAND_1: composer install
      STARTUP_COMMAND_2: NETTE_DEBUG=1 php bin/console migrations:migrate --no-interaction
      STARTUP_COMMAND_3: NETTE_DEBUG=1 php bin/console doctrine:fixtures:load --no-interaction
    networks:
        - traefik_proxy

  postgres:
    image: dockette/postgres:13
    environment:
      - POSTGRES_PASSWORD=contributte
      - POSTGRES_USER=contributte
      - POSTGRES_DB=contributte
    volumes:
      - .docker/data/postgres:/var/lib/postgresql/data
    networks:
        - traefik_proxy
    ports:
        - '5432:5432'

networks:
    traefik_proxy:
        external: true

volumes:
    pgdata:
